--Error Number
BEGIN TRY
	SELECT 1/0
END TRY
BEGIN CATCH
	SELECT ERROR_NUMBER() AS ERRORNUMBER
END CATCH

--ERROR SEVERITY
BEGIN TRY
	SELECT 1/0
END TRY
BEGIN CATCH
	SELECT ERROR_SEVERITY() AS ErrorSeverity
END CATCH

--ERROR STATE
BEGIN TRY
	SELECT 1/0
END TRY
BEGIN CATCH
	SELECT ERROR_STATE() AS ErrorState
END CATCH

--ERROR_PROCEDURE
CREATE PROCEDURE usp_ExampleProc
AS
	SELECT 1/0
GO
BEGIN TRY
	EXEC usp_ExampleProc;
END TRY
BEGIN CATCH
	SELECT ERROR_PROCEDURE() AS ErrorProcedure
END CATCH
GO

-- ERROR MESSAGE
BEGIN TRY
	SELECT 1/0
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS ErrorMessage
END CATCH

-- ERROR LINE
BEGIN TRY
	SELECT 1/0
END TRY
BEGIN CATCH
	SELECT ERROR_LINE() AS ErrorLine
END CATCH

-- ALL TOGETHER

IF OBJECT_ID('usp_GetErrorInfo', 'P') IS NOT NULL
	DROP PROCEDURE usp_GetErrorInfo;
GO

CREATE PROCEDURE usp_GetErrorInfo
AS
SELECT 
	ERROR_NUMBER() AS ErrorNumeber,
	ERROR_SEVERITY() AS ErrorSeverity,
	ERROR_STATE() AS ErrorState,
	ERROR_PROCEDURE() AS ErrorProcedure,
	ERROR_LINE() AS ErrorLine,
	ERROR_MESSAGE() AS ErrorMessage
GO

BEGIN TRY
	EXEC usp_ExampleProc;
END TRY
BEGIN CATCH
	EXEC usp_GetErrorInfo;
END CATCH