USE [master]
GO
/****** Object:  Database [SEDC_Db]    Script Date: 15.5.2024 19:55:11 ******/
CREATE DATABASE [SEDC_Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SEDC_Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SEDC_Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SEDC_Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SEDC_Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SEDC_Db] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SEDC_Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SEDC_Db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SEDC_Db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SEDC_Db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SEDC_Db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SEDC_Db] SET ARITHABORT OFF 
GO
ALTER DATABASE [SEDC_Db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SEDC_Db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SEDC_Db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SEDC_Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SEDC_Db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SEDC_Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SEDC_Db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SEDC_Db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SEDC_Db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SEDC_Db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SEDC_Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SEDC_Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SEDC_Db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SEDC_Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SEDC_Db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SEDC_Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SEDC_Db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SEDC_Db] SET RECOVERY FULL 
GO
ALTER DATABASE [SEDC_Db] SET  MULTI_USER 
GO
ALTER DATABASE [SEDC_Db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SEDC_Db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SEDC_Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SEDC_Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SEDC_Db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SEDC_Db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SEDC_Db', N'ON'
GO
ALTER DATABASE [SEDC_Db] SET QUERY_STORE = OFF
GO
USE [SEDC_Db]
GO
/****** Object:  Schema [hr]    Script Date: 15.5.2024 19:55:11 ******/
CREATE SCHEMA [hr]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 15.5.2024 19:55:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CustomerId] [int] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[City] [nvarchar](50) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 15.5.2024 19:55:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] NOT NULL,
	[Name] [nvarchar](150) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[Quantity] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [hr].[Employees]    Script Date: 15.5.2024 19:55:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [hr].[Employees](
	[EmployeeId] [int] NOT NULL,
	[Name] [nvarchar](150) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[Customers] ([CustomerId], [Name], [City]) VALUES (1, N'Risto', N'Skopje')
GO
INSERT [dbo].[Customers] ([CustomerId], [Name], [City]) VALUES (2, N'Slave', N'Skopje')
GO
INSERT [dbo].[Products] ([ProductId], [Name], [Price], [Quantity]) VALUES (2, N'Coca Cola', CAST(80.00 AS Decimal(18, 2)), 7)
GO
USE [master]
GO
ALTER DATABASE [SEDC_Db] SET  READ_WRITE 
GO
